name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: 3.208.173.73
        EC2_USERNAME: apienkow
      run: |
        # Create SSH directory and key file
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Add EC2 host to known hosts
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
        
        # Copy files to EC2 (excluding .env)
        scp -i ~/.ssh/deploy_key -r \
          dist \
          package.json \
          package-lock.json \
          deploy.sh \
          $EC2_USERNAME@$EC2_HOST:~/app/
        
        # Execute deployment
        ssh -i ~/.ssh/deploy_key $EC2_USERNAME@$EC2_HOST "
          cd ~/app && \
          chmod +x deploy.sh && \
          ./deploy.sh"