name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - CICD-tests
  pull_request:
    branches:
      - main
      - CICD-tests

jobs:
  build:    # First job name
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

      # Add Node.js setup
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # Specify Node.js version
        cache: 'npm'    # Enables npm caching

    # Install dependencies 
    - name: Install dependencies
      run: npm install

    # Run linting
    # - name: Run lint #need to install eslint dependency for this to run
    #   run: npm run lint

    # Run tests
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build

  # deploy:    
  #   needs: build    
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' # Only deploy when the branch is main

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Configure AWS credentials    
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-1

  #   - name: Deploy to EC2 # need to fix this doesn't work properly
  #     run: |
  #       echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
  #       chmod 600 deploy_key
  #       ssh -i deploy_key -o StrictHostKeyChecking=no ec2-user@3.208.173.73 'bash -s' < ./deploy/deploy.sh 