name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install dependencies (if you are using Node.js as an example)
    - name: Install dependencies
      run: npm install

    # Run linting
    - name: Run lint
      run: npm run lint

    # Run tests
    - name: Run tests
      run: npm test

    # Deploy to EC2
    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip 'bash -s' < ./deploy/deploy.sh
