- name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USERNAME: ec2-user
        EC2_HOST: "3.208.173.73" 
      run: |
        # Debug: List files to see where deploy.sh is
        ls -la
        ls -la deploy/
        
        # Create SSH directory and key file
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Add EC2 host to known hosts
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

        # Make deploy.sh executable before copying
        chmod +x deploy/deploy.sh
        
        # Copy files to EC2
        scp -i ~/.ssh/deploy_key -r \
          dist \
          run \
          src \
          package.json \
          package-lock.json \
          deploy/deploy.sh \
          $EC2_USERNAME@$EC2_HOST:~/app/
        
        # Execute deployment
        ssh -i ~/.ssh/deploy_key $EC2_USERNAME@$EC2_HOST "
          cd ~/app && \
          chmod +x deploy.sh && \
          ./deploy.sh"
