name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Create log directory
      run: |
        touch jest-output.log 
      
    - name: Set environment variables
      run: |
        echo "LOG_FILE=jest-output.log" >> $GITHUB_ENV
        echo "LOG_LEVEL=0" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=TESTaxad" >> $GITHUB_ENV 
        touch jest-output.log

    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USERNAME: ec2-user
        EC2_HOST: "3.208.173.73" 
      run: |
        # Create SSH directory and key file
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Add EC2 host to known hosts
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

        # Create app directory
        ssh -i ~/.ssh/deploy_key $EC2_USERNAME@$EC2_HOST "mkdir -p ~/app"

        # Make deploy.sh executable
        chmod +x deploy/deploy.sh
        
        # Copy files to EC2
        scp -i ~/.ssh/deploy_key -r \
          dist \
          run \
          src \
          package.json \
          package-lock.json \
          deploy/deploy.sh \
          src/process.config.js \
          $EC2_USERNAME@$EC2_HOST:~/app/
        
        # Execute deployment and start server
        ssh -i ~/.ssh/deploy_key $EC2_USERNAME@$EC2_HOST "
          cd ~/app && \
          chmod +x run && \
          npm install && \
          npm install -g pm2 && \
          ./run stop || true && \
          ./run serve"
